sudo: false

language: scala

branches:
  only:
    - develop
    - master

scala: 2.11.8

jdk: oraclejdk8

script:
  - sbt compile

# Email specific recipient all the time
notifications:
  email:
    recipients:
      - sohiljain.cs91@gmail.com
    on_success: always # default: change

after_install:
  - pwd
  - ls
  - which spark

deploy:
